### ISSUE TITLE
Replace custom CORS with CORS package

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/media-manager#5]
Instead of https://github.com/soixantecircuits/media-manager/blob/dev/server.js#L43 use the middleware recommanded https://expressjs.com/en/resources/middleware/cors.html

**Comment by negabakuru** [comment]
Done in https://github.com/soixantecircuits/media-manager/commit/30e7b9e73ab68ef98dfc1d6b598fd0316d242a5f
