### ISSUE TITLE
Add a `create-thumbnail` action

### ISSUE THREAD

**Issue by hugohil** [soixantecircuits/media-manager#7]
It would be pretty cool to have some `POST /api/v1/medias/:id/create-thumbnail` route that uses ffmpeg (or something else ?) to generate a thumbnail for the media.

It could accept dimensions as a parameter:

```json
{
  "width": 300,
  "height": 400
}
```

An Array to create severals:

```json
[{
  "label": "small",
  "width": 300,
  "height": 400
}, {
  "label": "medium",
  "width": 600,
  "height": 800
}]
```

We could even think further and add an `auto-thumbnail` setting that would automatically create the thumbnail if none is provided when the media is created.

Might have some time to work on this next week.

**Comment by emmanuelgeoffray** [comment]
Nope, we will do a micro-service with etna to generate thumbnail for videos.
And im-bro to generate thumbnails for images
